### PR TITLE
Change a stackoverflow tag

### PR DESCRIPTION
**Pull request by kastolom**
I just checked that there is no "load testing" tag on StackOverflow, there is "load-testing", so I changed it.

### CODE REVIEW

**Comment by direvius** [comment]
Thank you!

**Comment by kastolom** [comment]
Also I was going to create a new tag for Yandex.Tank, but it turned out that  there is such tag, and its name is [yat](http://stackoverflow.com/questions/tagged/yat) (it seems unclear to me), so you might want to add it here too. If you'd like I can create a tag yandex-tank on stackoverflow and make the yandex-tank and yat tags synonyms.

**Comment by direvius** [comment]
Yes, 'yat' seems pretty unclear to me, too. Actually I didn't know about it. So please create the new one.

**Comment by kastolom** [comment]
I've create the yandex-tank tag and thank you for the response on my question

**Pull request merged**
