### PR TITLE
Jmeter termination #327

### PR DESCRIPTION
**Pull request by c13**
There are problems when tank was sending SIGTERM signal to the Jmeter. I changed it to SIGKILL.

### CODE REVIEW

**Comment by f2nd** [comment]
It would be better to send SIGTERM and if jmeter is still running after some timeout SIGKILL.

**Comment by whetherharder** [comment]
what about using $jmeter_home/bin/shutdown.sh before sending SIGKILL ? It looks like more gracefull

**Comment by whetherharder** [comment]
It  will be enough to send "Shutdown" or "StopTestNow" on  4445 port by udp

**Comment by direvius** [comment]
fixed in #454

**Pull request closed without merging**
