### PR TITLE
new monitoring module - telegraf.

### PR DESCRIPTION
**Pull request by netortik**

### CODE REVIEW

**Comment by netortik** [comment]
not safe to merge before
https://github.com/yandex/yandex-tank/pull/219

old monitoring plugin should be updated.

**Comment by whetherharder** [comment]
Great idea to integrate tank with telegraf! Thanks much for your work.

I have a question about it`s output. Do you have any plans to push metrics directly to influxdb (or any other storage, provided by telegraf output plugins)  ? Or it is an important design concern to separate metrics storage from metrics collection ?

By the way, did you see [snap](https://github.com/intelsdi-x/snap)? Looks very promisingly, but very experimental)

**Comment by netortik** [comment]
You'll be able to specify as many output/input plugins for telegraf as you wish. So telegraf will be able to send metrics directly to influxdb as well. 

Thanks for snap. We'll see how we can use it.

**Comment by direvius** [comment]
We don't use influxdb or similar backends (graphite, etc) because of the specifics of our workload. Load tests are typically time-bounded (each one is at average 15 minutes) and different tests can have different metrics set. InfluxDB is designed to store continuous time series data, but we have short and chunked time series data which are not handled by InfluxDB (or Graphite) well. There are also difficulties in displaying such chunks: https://github.com/grafana/grafana/issues/3191

Besides of that it is good to have all metrics in one place and we think that it is the task for Yandex.Tank to get them there. Yandex.Tank collects response time characteristics and they should be placed somewhere near the corresponding monitoring metrics.

Howerver, there are plugins for Graphite and InfluxDB available in Yandex.Tank branch 1.7.* and we will update them to support 1.8.* as well.

**Comment by whetherharder** [comment]
@direvius I agree, influx is not ideal. Mainly because of growing cardinality.
But what are the most relevant alternatives for short timesiries in your opinion?

**Comment by direvius** [comment]
@whetherharder I think that a column-based DB would be an appropriate choice here, but we didn't try any opensource column-based DBs in practice. We have moved from MySQL to a proprietary DB about a year ago. I've heard there were plans to make it open-source in a month or two. I'll post a link here as soon as it becomes available.

**Comment by direvius** [comment]
@whetherharder the column-based DB that we use for our load tests data is open-sourced today: https://clickhouse.yandex

**Comment by whetherharder** [comment]
Thanks much ! I 've just read the news. You are the best)
15.06.2016 16:16 пользователь "Alexey Lavrenuke" <notifications@github.com>
написал:

**Pull request merged**
